language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report versioneye:update
