language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn versioneye:update
  - mvn clean cobertura:cobertura coveralls:report
